title: Doc Projet
description: Documentation du projet

# NE RIEN MODIFIER CI-DESSOUS SI VOUS N'ETES PAS CERTAINS DE CE QUE VOUS FAITES

# Thème
# remote_theme: Makerspace-Amiens/CraftTheDocs-V1.0
theme: just-the-docs
url: https://github.com/Makerspace-Amiens

# Paramètres optionnels de "Just the Docs"
just_the_docs:
  navigation_depth: 5
  search_enabled: false
  search_indexing: true
